[package]
name = "brainfrick"
version = "0.1.0"
authors = ["Gingeh <39150378+Gingeh@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "brainfrick"
path = "src/lib/lib.rs"
